# Generated by Django 2.2.8 on 2020-01-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit', models.TextField()),
                ('Mon', models.TextField()),
                ('Tue', models.TextField()),
                ('Wed', models.TextField()),
                ('Thu', models.TextField()),
                ('Fri', models.TextField()),
                ('Sat', models.TextField()),
                ('Sun', models.TextField()),
                ('Time', models.TextField()),
            ],
        ),
    ]
