# Generated by Django 2.2.8 on 2020-01-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='Fri',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='Mon',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='Sat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='Sun',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='Thu',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='Time',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='Tue',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='Wed',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit',
            field=models.TextField(null=True),
        ),
    ]
